### ISSUE TITLE
Ability to deploy Kyma with valid certificate through GCP Marketplace

### ISSUE THREAD

**Issue by derberg** [kyma-incubator/marketplaces#2] opened 2019-06-03 18:31 UTC
**Description**

When Kyma is deployed from **GCP Marketplace** it should be configurated with valid certificate instead of self-signed. Unfortunately, it is not possible to generate a valid cert for xip.io domain with Let's encrypt. We can consider a similar solution as proposed here: https://content.pivotal.io/blog/sslip-io-a-valid-ssl-certificate-for-every-ip-address

Also, it would be nice if the user will have an ability to configure his domain with a certificate.

**Reasons**

Have a better experience when Kyma is deployed from GCP Marketplace.

**Attachments**

https://content.pivotal.io/blog/sslip-io-a-valid-ssl-certificate-for-every-ip-address
https://letsencrypt.org
http://xip.io

**Comment by derberg** [comment] 2019-06-03 18:32
moved from https://github.com/kyma-project/kyma/issues/4132

**Comment by atakanyenel** [comment] 2019-08-02 22:15
I currently have an certbot implementation which installs kyma with a valid certificate to `*.my.kyma.cloud` hostname, which is managed by us. The problem is currently authentication. How can we differentiate requests coming from GCP from invalid requests. We need some kind of traceability of  the kyma users, otherwise everybody can run any website they want under our domain.

**Comment by hudymi** [comment] 2020-06-02 13:40
As we are not working actively on support for GCP Marketplace, I'm going to close this issue. We will rather focus on improvements related to Kyma installation, so probably the marketplace will be not needed. Also, the new WG around installation has started recently 😄

**Closed as completed by hudymi** 2020-06-02 13:40 UTC
Labels: enhancement, area/community
